# -*- coding: utf-8 -*-
"""Self-reflective Hint Extraction for SHPO (§3.5.2, Algorithm 1).

Implements the "the policy itself acts as a teacher" step of
Self-reflective Hint Policy Optimization: for every *mixed-outcome*
query (at least one correct and one incorrect rollout of the locator),
the locator contrasts its *own* correct trajectories o+ with its own
incorrect ones o- and distills a concise, domain-general corrective
hint **without leaking the ground-truth answer**, using the *Prompt
Template for Hint Extraction* (Appendix J).

By default the hint is generated by the locator policy itself
(self-hint, Algorithm 1 ``h <- T(o+, o-)`` with the deployed locator as
the teacher); pass ``--model <name>`` to delegate hint extraction to an
external teacher (e.g. ``gpt-4o-mini``).  The extracted hints are
appended to the prompts of the subsequent training stage by
``inject_hints.py`` (Eq. 25).

Input format (one JSON list; produced during SHPO rollouts):

    [
      {
        "input": ...,
        "question": ...,
        "answer": ...,
        "ground_truth_evidence": "<id>[7, 9]</id>...",
        "predictions": [
          {"predicted_id": "<id>[7, 9]</id>", "predicted_reason": "<reason>...</reason>"},
          ...
        ]
      },
      ...
    ]

Output: the same list augmented with a ``hint`` object
``{"divergence_step": ..., "strategy_hint": ...}``.

Example (self-hint, default):
    python hint_shpo.py \
        --input_path rollouts.json \
        --output_path rollouts_with_hints.json

Example (external teacher):
    python hint_shpo.py \
        --input_path rollouts.json \
        --output_path rollouts_with_hints.json \
        --model gpt-4o-mini
"""

import argparse
import json
import logging
import os
import re
import sys
from collections import Counter
from typing import Dict, List

from tqdm import tqdm

# share the LLM client and prompt templates with the MMR module
sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "MMR"))

from llm_client import LLMClient  # noqa: E402
from prompts import HINT_EXTRACTION, render  # noqa: E402

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

MAX_TOKENS = 8192
SAVE_EVERY = 20

# ===============================
# Hint-teacher client (§3.5.2)
# ===============================
def build_hint_client(model: str) -> LLMClient:
    """Build the client that generates the corrective hint.

    *Default (``--model`` unset) — self-hint.*  The policy itself acts as
    the teacher ``T`` (Algorithm 1: ``h <- T(o+, o-)``): the *deployed
    locator* (served via vLLM behind the ``LOCATOR_*`` endpoint, same as
    ``rel_generate.py``) reflects on its own correct / incorrect
    rollouts and distills the hint.

    *External teacher (``--model <name>``).*  A separate model (e.g.
    ``gpt-4o-mini``) served through the ``OPENAI_*`` endpoint generates
    the hint from the locator's rollouts.
    """
    if model:
        logger.info(
            "Hint teacher: external model '%s' (OPENAI_* endpoint)", model
        )
        return LLMClient(model=model, temperature=0.0, max_tokens=MAX_TOKENS)

    # self-hint: the locator policy itself is the teacher
    from openai import OpenAI  # noqa: E402

    model_name = os.environ.get("LOCATOR_MODEL", "judge")
    base_url = os.environ.get("LOCATOR_BASE_URL", "http://localhost:8000/v1")
    client = LLMClient(
        model=model_name,
        client=OpenAI(
            base_url=base_url,
            api_key=os.environ.get("LOCATOR_API_KEY", "EMPTY"),
        ),
        temperature=0.0,
        max_tokens=MAX_TOKENS,
        timeout=120,
    )
    logger.info(
        "Hint teacher: the policy itself (self-hint) via '%s' at %s",
        model_name,
        base_url,
    )
    return client


# ===============================
# Utils
# ===============================
def extract_ids(text: str):
    if text is None:
        return set()
    return set(re.findall(r"\d+", text))


def is_overlap(gt_ids, pred_ids) -> bool:
    """A rollout is correct iff all ground-truth IDs are contained in the
    predicted IDs (evidence-Localization correctness, Eq. 21)."""
    if not gt_ids:
        return False
    return gt_ids.issubset(pred_ids)


def sanitize_hints(hints_text: str) -> str:
    """Strip document IDs, dates, and overly specific content from hints."""
    if not hints_text:
        return hints_text
    # Remove document ID references like [22], Document [14]
    hints_text = re.sub(r"Document\s*\[\d+\]", "relevant document", hints_text)
    hints_text = re.sub(r"\[\d+\]", "", hints_text)
    # Remove date patterns
    hints_text = re.sub(
        r"\b(?:January|February|March|April|May|June|July|August|September"
        r"|October|November|December)\s+\d{1,2},?\s+\d{4}\b",
        "[DATE]",
        hints_text,
    )
    hints_text = re.sub(r"\b\d{4}-\d{2}-\d{2}\b", "[DATE]", hints_text)
    return hints_text


def parse_hint_json(raw: str) -> Dict:
    """Parse the JSON object returned by the hint extraction prompt."""
    text = (raw or "").strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:]
        text = text.strip()

    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end > start:
        try:
            obj = json.loads(text[start : end + 1])
            hint = obj.get("hint", obj)
            divergence = str(hint.get("divergence_step", "")).strip()
            strategy = str(hint.get("strategy_hint", "")).strip()
            if strategy:
                return {"divergence_step": divergence, "strategy_hint": strategy}
        except json.JSONDecodeError:
            pass
    # fallback: treat the raw text as the strategy hint
    return {"divergence_step": "", "strategy_hint": text}


# ===============================
# Main
# ===============================
def process_file(input_path: str, output_path: str, client: LLMClient):
    """Extract self-reflective hints for all mixed-outcome queries."""

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Resume from checkpoint
    processed_ids = set()
    if os.path.exists(output_path):
        with open(output_path, "r", encoding="utf-8") as f:
            existing = json.load(f)
            for item in existing:
                processed_ids.add(item.get("input"))
            new_data = existing
            logger.info("Resuming: loaded %d processed samples", len(existing))
    else:
        new_data = []

    stats = Counter()

    for idx, sample in enumerate(tqdm(data, desc="Processing")):
        if sample.get("input") in processed_ids:
            continue

        gt_ids = extract_ids(sample.get("ground_truth_evidence", ""))

        pos_preds = []
        neg_preds = []
        for pred in sample.get("predictions", []):
            pred_ids = extract_ids(pred.get("predicted_id", ""))
            if is_overlap(gt_ids, pred_ids):
                pos_preds.append(pred["predicted_reason"])
            else:
                neg_preds.append(pred["predicted_reason"])

        # only mixed-outcome queries yield contrastive hints (Algorithm 1)
        if pos_preds and neg_preds:
            stats["partial"] += 1

            prompt = render(
                HINT_EXTRACTION,
                Question=sample.get("question", ""),
                CorrectTrace="\n".join(pos_preds),
                WrongTrace="\n".join(neg_preds),
                Answer=sample.get("answer", ""),
            )

            response = client.chat(prompt)
            if not response:
                stats["error"] += 1
                continue

            hint = parse_hint_json(response)
            hint["strategy_hint"] = sanitize_hints(hint["strategy_hint"])
            sample["hint"] = hint
            # backward-compatible flat field
            sample["hints"] = hint["strategy_hint"]

            new_data.append(sample)
            processed_ids.add(sample.get("input"))
        else:
            stats["skipped"] += 1

        # Incremental save
        if len(new_data) % SAVE_EVERY == 0:
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(new_data, f, indent=2, ensure_ascii=False)
            logger.info("Saved %d samples", len(new_data))

    # Final save
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(new_data, f, indent=2, ensure_ascii=False)

    print("\n===== DONE =====")
    print(f"Total: {len(data)}")
    for key, value in stats.items():
        print(f"{key}: {value} ({value / len(data):.2%})")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Self-reflective hint extraction for SHPO (§3.5.2)"
    )
    parser.add_argument("--input_path", type=str, required=True)
    parser.add_argument("--output_path", type=str, required=True)
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="external teacher model for hint extraction (e.g. gpt-4o-mini). "
        "Omit to let the locator policy itself act as the teacher "
        "(self-hint, paper §3.5.2); the deployed locator is resolved from "
        "LOCATOR_MODEL / LOCATOR_BASE_URL / LOCATOR_API_KEY.",
    )
    args = parser.parse_args()
    client = build_hint_client(args.model)
    process_file(args.input_path, args.output_path, client)
